// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi2qVq3gMOgve0no057hpiR13o6gW3rA4',
    appId: '1:41130948927:web:159f336b098c0c7cf43b8a',
    messagingSenderId: '41130948927',
    projectId: 'hackathon-b64ba',
    authDomain: 'hackathon-b64ba.firebaseapp.com',
    storageBucket: 'hackathon-b64ba.appspot.com',
    measurementId: 'G-ZC69Q3SW5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcLUsNcovBojtjwilwg6Kf5pFQmvgLLHE',
    appId: '1:41130948927:android:0da3fd4acc7cb772f43b8a',
    messagingSenderId: '41130948927',
    projectId: 'hackathon-b64ba',
    storageBucket: 'hackathon-b64ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCVU_6lK-ToB2DtHWXNToilh_40PYTYpE',
    appId: '1:41130948927:ios:61173c6b87a49f8cf43b8a',
    messagingSenderId: '41130948927',
    projectId: 'hackathon-b64ba',
    storageBucket: 'hackathon-b64ba.appspot.com',
    iosBundleId: 'com.example.crop1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCVU_6lK-ToB2DtHWXNToilh_40PYTYpE',
    appId: '1:41130948927:ios:61173c6b87a49f8cf43b8a',
    messagingSenderId: '41130948927',
    projectId: 'hackathon-b64ba',
    storageBucket: 'hackathon-b64ba.appspot.com',
    iosBundleId: 'com.example.crop1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi2qVq3gMOgve0no057hpiR13o6gW3rA4',
    appId: '1:41130948927:web:5389506601a76845f43b8a',
    messagingSenderId: '41130948927',
    projectId: 'hackathon-b64ba',
    authDomain: 'hackathon-b64ba.firebaseapp.com',
    storageBucket: 'hackathon-b64ba.appspot.com',
    measurementId: 'G-B2HH2PFEE3',
  );
}
